name: Codacy codacy-coverage-reporter CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest
    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@${GITHUB_REF##*/}
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@${GITHUB_REF##*/}
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
